name: 'Vuepress deploy'
description: 'A GitHub Action to build and publish Vuepress sites to GitHub Pages'
author: 'chenyaru1205'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'upload-cloud'
  color: 'gray-dark'